name = "Optimised for Rats"
author = "SewerBunny"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c474e43fae319f1cb0aa048f1bf38aaefbdacf4cccf790939105546a151437f"

[versions]
fabric = "0.14.8"
minecraft = "1.19.2"
