name = "Optimised for Rats"
author = "SewerBunny"
version = "1.2.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1dfafdbb24225e8b572df2e903e4a863339936f9526c2b8a283fe84eed9f917f"

[versions]
fabric = "0.14.9"
minecraft = "1.19"
