name = "Optimised for Rats"
author = "GlitchyBunny"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9df6e7fe0eb6a8ecaf8d4824a99c02f9965fbb0ae68af737ac00fe8adff84929"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.2"
