name = "Optimised for Rats"
author = "SewerBunny"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "add1085832f4ab6420ec1191740b965cbabf375702c9fc775ccc8e11319d5ddb"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
