name = "Optimised for Rats"
author = "SewerBunny"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5be601c9a881340c94b1f1594b7a59be575b02d4db80e46ad869aa51913517f2"

[versions]
fabric = "0.14.8"
minecraft = "1.19.2"
