name = "Optimised for Rats"
author = "SewerBunny"
version = "1.2.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4f884df6b69d81b0f5459e38737d6299a80c053ee2bfff44739dee7769bf6c2"

[versions]
fabric = "0.14.9"
minecraft = "1.19"
