name = "Rats Optimised"
author = "SewerBunny"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2cc487f84bffdbdef8ddbebb76248662f8bdd1ddd2ca6d65cfe6d9c23c0e2aed"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
