name = "Optimised for Rats"
author = "SewerBunny"
version = "1.2.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c87741eeb6e985155677b9d4d6cc81f5d41ad76922e8f176719b9a5ace5010f3"

[versions]
fabric = "0.14.9"
minecraft = "1.19"
