name = "Optimised for Rats"
author = "SewerBunny"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b83235a6c8f725a55f1a0c58f2df0f62e8059eee5e3a44dc14ab9415f95be932"

[versions]
fabric = "0.14.8"
minecraft = "1.19.1"
