name = "Optimised for Rats"
author = "SewerBunny"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c620a12324601dbaf7c3d434eabab02913dc5cb8587d6e6c14a16b0caf865305"

[versions]
fabric = "0.14.8"
minecraft = "1.19.2"
