name = "Optimised for Rats"
author = "SewerBunny"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6523c4073a0003dc35bc0d637312fc71aa35759eb8261e83c78f1c44375e2f0e"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
