name = "Optimised for Rats"
author = "SewerBunny"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31ed20decb77759cf324ec60527e351c88d1e8b75107394e9b32c221e1228d28"

[versions]
fabric = "0.14.8"
minecraft = "1.19.2"
