name = "Optimised for Rats"
author = "SewerBunny"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c1e781cb5904e5c7a61648fdd0a32c46c2e1a43938c7d4bc6d0412e16d7a7ea"

[versions]
fabric = "0.14.8"
minecraft = "1.19.1"
